### ISSUE TITLE
Allow New Registrations does not work as anticipated.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#104]
To replicate:
1. Navigate to any sub-company, take note of your company ID.
2. Select the checkbox next to "Allow new registrations" under the Network tab.
3. In an incognito browser, navigate to http://rva.risevision.com?parentId="Your company ID noted in step 1".
4. Sign up for a new account.

What this does:
This creates a new company in Rise Vision, independent of the company ID used in the link.

What this should do:
This should create a sub-company below the parent company modified in step 1.

http://content.screencast.com/users/btfrise/folders/Snagit/media/44268b69-f431-4e72-85ca-5a84b9df5bad/2015-07-09_09-58-58.png

Since we have removed other White Labeling options for the time being, and it's so easy to create sub-companies, we should just remove this from the Network UI.

**Comment by ByronDarlison** [comment]
Won't fix in RVA
