### ISSUE TITLE
Cannot access RVA from an iOS device using the Chrome browser.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#108]
Steps to reproduce:
1. Using an iOS device with the Chrome browser, access rva.risevision.com
2. Sign in to your Rise Vision account

Result:
Once signed in, you will receive an infinite spinner. No page content will load or be accessible.

How it should work:
RVA should load and be fully accessible.

OS:
iOS 8.4

Chrome Ver:
44.0.2403.67

**Comment by btfrise** [comment]
@ByronDarlison FYI

**Comment by ByronDarlison** [comment]
@btfrise is this a priority? I would rather address with the new apps. And curious, does it happen with displays.risevision.com? Thanks!

**Comment by btfrise** [comment]
@ByronDarlison this is not a priority, but it is something that should be noted and looked at in the future.

It does occur in the displays and storage apps as well.

**Comment by ByronDarlison** [comment]
Okay @btfrise. Thanks @alex-deaconu @rodrigopavezi do you guys have ipads that you can check stuff on?

**Comment by alex-deaconu** [comment]
@ByronDarlison I do have an iPad (1st gen) but it's too old to install Chrome on. Will try on the iPhone. Thanks.

**Comment by rodrigopavezi** [comment]
@ByronDarlison I have an Ipad but it is not with me at the moment. I will though take it tomorrow so I can test it. cheers

**Comment by ByronDarlison** [comment]
Will not fix in RVA
