### ISSUE TITLE
PUD Functionality not working with Video Folder Widget

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rva#122]
Original presentation: http://rva.risevision.com/#/PRESENTATION_MANAGE/id=7f425e76-e73e-493c-bc86-0c15fcb18734?cid=4ebf4461-1830-4ec2-a9bd-64cc32e60499

Preview: http://preview.risevision.com/Viewer.html?type=presentation&id=7f425e76-e73e-493c-bc86-0c15fcb18734

Reproduction Steps

Created a folder in storage and uploaded 2 videos
Created placeholder, implemented video folder widget
Added RSS feed to the placeholder 
In video folder configuration, selected “play until done”

Expected results: 

Each video should play until done before moving on to the next one.

Actual results:

Videos will not play at all, only the RSS feed will show. I had to manually input the duration and unselect ‘play until done’ in order for the videos to play. I tried placing the widget at the top of the playlist but still run into the same issue. 

<img width="1051" alt="screen shot 2015-10-07 at 10 48 42 am" src="https://cloud.githubusercontent.com/assets/11686685/10341135/7839ac58-6ce1-11e5-91c2-1bf3eb1469df.png">

**Comment by ByronDarlison** [comment]
@sheadarlison is this issue in the new editor or the old editor, or both? Thanks

**Comment by sheadarlison** [comment]
@ByronDarlison Ashleigh experienced it with old, I did not. However, I did experience it with new so i'll put it there as well. 

Thanks

**Comment by ByronDarlison** [comment]
@sheadarlison @ashleighalmeida is this issue still open with the new editor? Thanks

**Comment by ashleighalmeida** [comment]
@ByronDarlison I wasn't able to recreate this, (the new editor doesn't support RSS) - I tested with text and didn't encounter an issue. I haven't heard word from this, so closed.

**Comment by ByronDarlison** [comment]
Thanks
