### ISSUE TITLE
Multiple instances of a placeholder being created in RVA

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rva#123]
Multiple instances (or playlist items) of the placeholder (ie an image item, a HTML item, a widget) is being created in RVA.

**How to Duplicate** 
1. Copy original code from user from RVA (see presentation id=2d46860c-ae25-4ec2-8af7-e0b728b4df96 from cid=43eb03e1-23d7-4955-802a-e69e3721947e)
2. Go to own RVA and paste code
3. Rename the template and stay within HTML
4. RVA goes to Design
5. View the Placeholders
6. Duplicates have occurred: 
Cover frame for presentations - Image item
Footer text - Text item
HKA_Logo_2 - Image item
Presentations - HTML item
Twitter - HTML item
clock - World Clock widget
7. Go back to HTML and copy code to compare
8. Repeat a second time using ‘non duplicated’ code. Problem is duplicated.

Original version from User with no duplicates: 407 lines of code 
Own with duplicates: 539 lines of code 

Environment: Same as user (Mac, same v of Chrome), in RVA not new Editor even though user mentions going to Editor.

The same presentation code was presented in the new Editor and the problem was not duplicated.
If the same presentation code was presented in Editor, and then back into RVA, the problem was duplicated.

**Comment by ezequielc** [comment]
RVA has problems importing a HTML code that is created in the new editor due to how js numbers are saved in the new editor.
For instance, new editor handles both "duration": 10 (number) and "duration": "10" (string)
RVA seems to accept only strings.

**Comment by ezequielc** [comment]
@alex-deaconu What do you think would be easier? Should we support both types in RVA or make the new editor HTML present numbers as strings? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc the RVA should support both types. I thought it did, I will double check. Thanks.

**Comment by alex-deaconu** [comment]
@ezequielc actually this issue is related to a missing field; the `index` field was not being added to the playlist items in the new Editor. However, I fixed this in the RVA by no longer checking/requiring the `index`.

Fixed at http://1-08-027.rvauser2.appspot.com/. @lapinnoir can you please verify?

Thanks!

**Comment by ezequielc** [comment]
@alex-deaconu it is workign for me. Thanks

**Comment by lapinnoir** [comment]
@alex-deaconu @ezequielc Thanks just did steps on http://1-08-027.rvauser2.appspot.com/ and can verify it works. :+1:
