### ISSUE TITLE
Display distribution is not permanent when switching to the HTML tab.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#128]
Steps to reproduce:
1. Add multiple content items to a placeholder.
2. Change one of these items to only appear on one or two displays.
3. Save the placeholder, and switch to the HTML tab.
4. Switch back to the Design tab.

Result:
The distribution to only one or two displays in step 2 has been erased, and now the item is set to appear on all displays.

How it should work:
The display configuration should be permanent when switching between HTML and Design tabs.

**Comment by ByronDarlison** [comment]
Will not correct in RVA. @btfrise can you confirm this issue isn't happening in new editor? And if it isn't can you close this defect. Thanks

**Comment by btfrise** [comment]
Fixed in Editor FYI @ByronDarlison
