### ISSUE TITLE
No End Date setting does not work in Schedule

### ISSUE THREAD

**Issue by lapinnoir** [Rise-Vision/rva#131]
When I specify No End Date to an existing Schedule in RVA, the setting resets when I revisit the Schedule again.

**How to duplicate**
1. In RVA, create a new Schedule. Set to the timeline to 'Daily' and select 'No End Date' and Save.
2. Go back into to the Schedule timeline. Unselect 'No End Date' and input a future date. Save.
3. Go back to the Schedule timeline. Select 'No End Date' again which should wipe out the Calendar entry for the End Date and Save.
4. Go to another page then back to that Schedule and notice that 'No End Date' is unselected.

If the Schedule's End Date was wiped out in the **new Schedules app, we don't see this issue**.

The current workaround right now is to: 
1. Get user on the new Schedules app when they edit Schedules with No End Date
2. If the user lands in RVA they need to create a new Schedule.

http://g.recordit.co/VI2kjcMhgM.gif

**Comment by lapinnoir** [comment]
https://app.intercom.io/a/apps/d85f4ah4/inbox/conversation/1718323379

**Comment by robb-price** [comment]
@lapinnoir When we run into this, can we just tell users to use the new Schedules App, and that will solve the problem?

**Comment by lapinnoir** [comment]
@robb-price Yes.   This has come up a couple of times at least via Intercom to me.  Would also be useful to have Schedules in RVA automatically redirected to the new Schedules app if that's in the pipeline.

**Comment by robb-price** [comment]
@lapinnoir if switching to the new Schedules App will solve the issue, let's just recommend that. We don't want to put any effort into the older Schedules option if we don't need to.

We can decide to revisit at a later date if we need to.
