### ISSUE TITLE
Endpoint generation/documentation missing

### ISSUE THREAD

**Issue by myspivey** [Rise-Vision/rva#139]
Without anyway to generate endpoints or even understand the server architecture, there is no way to setup a local or non destructive environment that we can test on as non employees of Rise Vision. Is there a way to supply this so that we can contribute to RVA core? Reading the README it looks like this should be available but I can not find a source for this anywhere. Appreciate any guidance on this.

**Comment by ezequielc** [comment]
Hi @myspivey!
We don't provide a local environment for development, you will need to register and use our API. 
You can check the API documentation here: https://help.risevision.com/developer
Thanks!

**Comment by myspivey** [comment]
I see @ezequielc. That seems odd based off these two bullet points from the README.

> If you want to use our code to make something that is specific to you, and that doesn’t fit with what we want to do, we don’t want to get in your way. Take our code and make just what you need.
> 
> We know that some of you nervous types worry about what happens if our company gets taken out in the zombie apocalypse. We get it, and neither one of us wants to deal with that delicate question of software escrow agreements for the “just in case we kick the bucket scenario”. No worries! We made it easy. No fuss, no cost, no lawyers! We published the software here. Have at it.

It would be impossible to make it our own or contribute or continue it if there is no way to develop against a separated environment instead of a production environment which is what the API seems to expose. We have no ability to validate the data is saved properly on a backend or see how it is going through transport and being properly formed. Even looking at widget development there is no real way to validate against the API. The code that is in github appears to be missing large swaths of functionality that forms the entire product. Just looking at the network JSON shows that not matching the object model from RVA. This makes any sort of contributive development physically impossible without the full picture. I guess that leads me to ask why open source this for us to help but not give us the pieces we need to contribute. It seems superficially open sourced. Am I missing something there?

**Comment by ezequielc** [comment]
@myspivey we appreciate your for the feedback, but at this time our server is not open sourced and we have no plans to do so. 
Also, RVA is deprecated, that is why the response does not match the documentation anymore. We suggest you to take a look at our [new Editor](https://github.com/Rise-Vision/rise-vision-apps/). We will work to improve RVA documentation to mention this fact. 
And if there is something we can help with now so you can move forward, please let us know.
Thanks!

**Comment by myspivey** [comment]
Is there some sort of guide to what is deprecated and not? Roadmap, changelogs? I saw new editor was still communicating with rva.risevision.com which looks like it would be this product (until you see the object model). Makes it confusing as to what is what. Especially with active commits still here. 188 repositories is a lot to sort through as to which pieces fit where and what's active vs not. Appreciate the time. You can close it after this as this appears to not really be a true open source project so negates my original bug.

**Comment by ezequielc** [comment]
@myspivey I understand your frustration, the best way to keep track of the changes is by checking our Community (https://community.risevision.com). Cheers!
