### ISSUE TITLE
Subscribe now font color should be white

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rva#141]
When opening the Priority Support subscription dialogs, the text in the link appears as blue. It should be white instead.

https://www.screencast.com/t/CUtsBYI6J & https://www.screencast.com/t/KPZQQVN09PcH.

Issue only seems to occur in the RVA, and is probably propagated from the subscription-status-component.

Thanks.

**Comment by ezequielc** [comment]
@alex-deaconu Can we close this? Thanks

**Comment by alex-deaconu** [comment]
@ezequielc you're right. Missed this. Thanks.
