### ISSUE TITLE
Cannot get to classic editor

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/rva#161]
Navigate to rva.risevision.com (or select Classic Editor from drop down menu in Apps, or open a presentation with depricated items - when prompted to open in Classic Editor, do so).   Once at rva.risevision.com, there are no links across the top of the page for Presentations, Gadgets, Schedules or Displays.   There is no way to see the list of presentations so that you can open the presentation in the classic editor.
<img width="1391" alt="screen shot 2018-01-23 at 11 27 01 am" src="https://user-images.githubusercontent.com/16138710/35290667-83d859ee-0030-11e8-98b7-58c68d7cb395.png">

**Comment by raydurkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) [Issue #161] Can't get to Classic Editor](https://trello.com/c/Hp94xzJ9/7100-1-issue-161-cant-get-to-classic-editor)

**Comment by alex-deaconu** [comment]
@raydurkin a fix for this issue has been deployed. Please validate. Thanks!

**Comment by raydurkin** [comment]
@alex-deaconu I have confirmed that all clients reporting this issue now report that it has been resolved.  Thank you!
