### ISSUE TITLE
Presentation list in RVA is showing HTML Presentations but RVA cannot handle them

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rva#184]
<img width="1414" alt="Screen Shot 2019-07-02 at 11 58 44 AM" src="https://user-images.githubusercontent.com/7738553/60524616-457ebb80-9cc3-11e9-8a01-9e0879feb690.png">

### What happens
RVA lists HTML Presentations, but opens a blank presentation when clicking on them.

### What should happen instead
RVA should filter and not list HTML Presentations

**Comment by sheadarlison** [comment]
@ezequielc how much effort to just open the template in a new tab in the template editor?

**Comment by ezequielc** [comment]
@sheadarlison More or less the same effort as filtering them from the list.

Another idea we were discussing is if it would make sense to remove the Presentations and Schedules list from RVA and point users to Apps, same as we did for Displays in RVA. Whenever we detected there are Gadgets in the Presentation, we could open in RVA, gradually moving users over to Apps and removing functionalities from RVA. Thanks!

**Comment by sheadarlison** [comment]
@ezequielc How much effort is the second idea?

**Comment by ezequielc** [comment]
@sheadarlison We will evaluate the effort on that idea once we get to the issue and let you know. It requires some thinking to not miss any cases. Thanks

**Comment by sheadarlison** [comment]
@ezequielc I think we should stick with opening the template editor in a new tab, I want to reduce complexity and get us to this quarters goals as quick as possible.

**Comment by ezequielc** [comment]
@sheadarlison Makes sense. Thanks!

**Comment by alex-deaconu** [comment]
@sheadarlison a fix for this issue has been deployed. To confirm, HTML Templates will now open the Template Editor in Apps in a new Window once selected from the RVA Presentations list. Thanks.
