### ISSUE TITLE
Adding HTML Presentation to a Schedule causes Display error

### ISSUE THREAD

**Issue by ezequielc** [Rise-Vision/rva#185]
### What happens
When adding a HTML Presentation to a Schedule in RVA, the Display failed to load, showing the Viewer spinner indefinitely.

### What should happen
When adding a HTML Presentation to a Schedule in RVA, Display should show the content properly.
Alternatively, we should remove the Schedules functionality from RVA and forward users to Apps.

**Comment by ezequielc** [comment]
@sheadarlison fyi. Let me know your thoughts. Thanks

**Comment by sheadarlison** [comment]
@ezequielc I think we should just forward users to apps when they click the schedules button in RVA, but is there any reason we shouldn't do that?

**Comment by ezequielc** [comment]
@sheadarlison I don't see a reason. I took a look and doesn't seem there is any functionality exclusive from RVA. We can safely forward them. Thanks!
@alex-deaconu fyi

**Comment by sheadarlison** [comment]
Awesome thanks

**Comment by alex-deaconu** [comment]
@sheadarlison a fix for this issue has been deployed. As suggested, we are forwarding Schedules to Apps (similar to Displays) within the RVA. Thanks!

**Comment by sheadarlison** [comment]
Thanks!
