### ISSUE TITLE
Pass Company Id to storage

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rva#59]
Add companyId in the url as part of the storage.risevision.com link.

**Comment by ByronDarlison** [comment]
@alex-deaconu is this addressed by this card https://trello.com/c/RKMRhnAm ? Thanks

**Comment by ByronDarlison** [comment]
@alex-deaconu @robb-price could you let me know the status of this issue? Is it closed now? Thanks

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu I can see the Company ID when I am in the main Company that the user belongs to, but it does not show when I switch to a Sub Company.

**Comment by alex-deaconu** [comment]
@ByronDarlison @robb-price I believe this issue is related to https://github.com/Rise-Vision/common-header/issues/487. Will fix both at once. Thanks.

**Comment by ByronDarlison** [comment]
Thanks @alex-deaconu given this I am closing this issue.
