### ISSUE TITLE
Can't create Users with Mixed Case or UPPER CASE usernames/emails in RVA

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rva#63]
<b>How it works now:</b>
Create a user with a MixedCase or UPPERCASE username/email address. Notice that it does not allow you to save this user. 

It does allow you to save this user in Common Header.

**Comment by ByronDarlison** [comment]
@robb-price is this resolved in the CH and if it is can we close this? Thanks

**Comment by robb-price** [comment]
@ByronDarlison I will test this today and update accordingly.

**Comment by robb-price** [comment]
@ByronDarlison Confirmed that this is working as expected with CH. Closing this issue.
