### ISSUE TITLE
Scale to fit breaks Fade transition.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#64]
When a placeholder is set to display images set to "scale to fit", the fade transition stops working.

Test case - 
Added four 2160 × 3842 images to a 1080x1920 placeholder.
Set all to scale to fit.
Set transition to fade.
No fade transition.

Resized all four images to 1080x1920
Removed scale to fit.
Set transition to fade.
Fade transition works.

**Comment by alanclayton** [comment]
@btfrise Do you get the same result on both native player and chrome app player?

**Comment by btfrise** [comment]
@alanclayton The transition does not work with scaled images in either native or CAP.

**Comment by alanclayton** [comment]
@btfrise if the issue occurs in Viewer then this should go in the Viewer repo. If it doesn't occur in Viewer it should go in the Player repo(s). Can you confirm and create new issues (and close this one) as necessary.

**Comment by btfrise** [comment]
@alanclayton noted. Bugs reported in both player repos. Closing this.
