### ISSUE TITLE
Enabling http to https redirection on storage.risevision.com breaks in-app storage functionality

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#69]
Steps to reproduce:

1. Configure webserver (nginx) to redirect http traffic to https (using ngx_http_rewrite_module).
2. In a presentation, add a placeholder.
3. In the placeholder, add an image.
4. Click on storage to specify a URL.
5. Click on the name of an image to select it for use in the presentation.

Result:  Nothing happens.  Further, the "x" in the top right corner will not close the box, either.

How it should work:  File selection modal should disappear and populate the image url field with the actual address to the file.

Link to Presentation:   N/A
OS:  Linux and Mac confirmed, presumably affects all of them.
Chrome version:  Version 40.0.2214.115 (64-bit)
Discovered via ticket: https://risevision.zendesk.com/agent/tickets/4956

Change has been rolled back and is working normally again (and ticket has been closed).

FYI:  @alanclayton

**Comment by ByronDarlison** [comment]
@mfisher11 @alex-deaconu @tejohnso @alanclayton should we put this issue on hold and fix this with the new version of the ux? Thanks

**Comment by tejohnso** [comment]
Sounds good to me.

**Comment by alanclayton** [comment]
That works

**Comment by mfisher11** [comment]
Sounds good.

**Comment by alex-deaconu** [comment]
Okay with me. Thanks!

**Comment by ByronDarlison** [comment]
Closing

**Comment by ByronDarlison** [comment]
I lied, reopening and marking wontfix. Thanks
