### ISSUE TITLE
No prompt to type DELETE when deleting a user account

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#73]
This is testing new (production) rva from:
http://1-08-001.rvauser2.appspot.com/

Steps to reproduce:
- delete a user account

Result:
- user is prompted with an okay/cancel dialog to delete
http://www.screencast.com/t/HbJxf8SHeMBL

How it should work:
- the current (default) version of rva prompts users to type DELETE before an account is removed

Link to Presentation:
N/A

OS:
Xubuntu 14.04.2 & 
Mac OS X

Chrome Ver:
Version 41.0.2272.89 (64-bit)

**Comment by ByronDarlison** [comment]
@mfisher11 @alex-deaconu @alanclayton I would like to mark this defect as won't fix and address in new ux. Do you guys concur? Thanks

**Comment by alanclayton** [comment]
I concur.

**Comment by mfisher11** [comment]
Sounds good.

**Comment by alex-deaconu** [comment]
Okay by me. Thanks.

**Comment by ByronDarlison** [comment]
Closing
