### ISSUE TITLE
When in a sub-company, clicking an app in the App Launcher places you in the account where you are a registered user

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#74]
Steps to reproduce:
1. Go into a sub-company
2. Open the App Launcher
3. Click on an App (confirmed with editor, store, storage, displays, and schedules)

Result:
Content (appropriate for the App) is listed for the account where you are a registered user

How it should work:
Content (appropriate for the App) is listed for the current sub-company.

Link to Presentation:
N/A

OS:
Xubuntu 14.04 and OSX

Chrome Ver:
Version 41.0.2272.89 (64-bit)

**Comment by alex-deaconu** [comment]
@mfisher11 @alanclayton as mentioned, this is a CH issue. Also, is this issue a priority for releasing the RVA OAuth2 conversion? Thanks.

**Comment by alanclayton** [comment]
@mfisher11 can you close this and log it in the CH repo.

@alex-deaconu Yes, i think we should fix this with RVA oAuth2 changes. Do you think it will require a bunch of time to fix?

**Comment by alex-deaconu** [comment]
@alanclayton no it shouldn't take too much time. It's a matter of duplicating the exact same functionality from the RVA to CH: attaching the `cid=*` parameter to the URL. Same idea as this issue: https://github.com/Rise-Vision/common-header/issues/469. 

However, I think it's ugly, the fact that we have the exact same links in 2 places, next to each other. I'm wondering if this navigation is something we can work on. Just a thought.

Thanks.

**Comment by alanclayton** [comment]
@alex-deaconu Change of plans....don't worry about addressing this now. We can do it after the oauth2 stuff is done. Thanks

@mfisher11 let me know when you have this issue recreated in the CH repo. Thanks

**Comment by mfisher11** [comment]
@alex-deaconu  @alanclayton   I just added it.  Issue #487.   Closing this one.
