### ISSUE TITLE
Using the new RVA, RPC errors still occasionally appear after changing from a sub-company to top-level

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#75]
Steps to reproduce:
- Unable to consistently reproduce.  Will update if I figure out a reliable way.
- It seems to happen most, when switching back from a sub-company to "My Company" and then clicking on Presentations, Gadgets, Displays, etc.

Result:
- RPC error is shown in system notification bar

How it should work:
- expected content should be displayed, and no RPC error.

Link to Presentation:
N/A

OS:
Xubuntu 14.04, OSX

Chrome Ver:
Version 41.0.2272.89 (64-bit)

**Comment by mfisher11** [comment]
Way to consistently reproduce the bug:

1. Go into a company (top level or sub, it doesn't matter)
2. Open up a presentation, schedule, display.  You must be IN one of these items, not at the category index which lists them.
3. Switch to a sub-company (or My Company) that does not have that particular presentation/schedule/display/gadget.

**Comment by alex-deaconu** [comment]
@alanclayton @mfisher11 this issue has to do with permissions the the particular resource. When a user switches companies, the resource no longer is accessible from that company (since access requires a correct company id). What needs to be done is redirect the user back to the List page or Start page. 

Also, to note is that the Company switching functionality was disabled in the RVA when the user entered a "Manage" page.

Thanks.

**Comment by alanclayton** [comment]
@mfisher11 I don't think this is a common scenario is it? If you agree, let's just leave this one for now.

**Comment by mfisher11** [comment]
@alanclayton It's probably not all that common for normal users.  I had noticed it a couple of times, then yesterday Ray came back mentioning that he gets the message 40-50% of the time (prior to identifying the actual cause).  If that's the way you're leaning, do we leave the issue open, but cross it off the checklist on trello?

**Comment by alanclayton** [comment]
@mfisher11 Yes, leave this open and cross it off the checklist.

**Comment by alex-deaconu** [comment]
@alanclayton @mfisher11 from my perspective, I've already tried 2 different fixes for this, none worked correctly. Kinda glad we're dropping it, at least from the initial release. Thanks.
