### ISSUE TITLE
Stock Selector for Financial Chart Gadget appears behind the Placeholder edit box

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/rva#76]
Steps to reproduce:
1. Add the Financial Chart gadget to a presentation
2. Click the Stock Selector

Result:
The Stock Selector appears behind the Placeholder edit window and you cannot search for or select stocks

How it should work:
The Stock Selector should appear in front so you can search and add stocks with it

Screenshot of issue:
http://screencast.com/t/EbK3rIVz

Link to Presentation:
N/A

OS:
Windows 7 64-bit

Chrome Ver:
Version 41.0.2272.89 m

**Comment by alex-deaconu** [comment]
@mfisher11 this is now fixed. Also fixed the font selector along with this. Thanks.

**Comment by mfisher11** [comment]
@AlexKolenoff FYI.
