### ISSUE TITLE
Show Rise Vision start page when user is logged out

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rva#77]
@alanclayton @mfisher11 logged this for tracking purposes.

Also, quick note: the Rise Vision start page URL will have to be hardcoded in the App. Since the User is logged out, we cannot call any API to retrieve the URL from the settings. Let me know if you think this could cause issues - I know we've had issues with static URLs in the past..

Thanks!

**Comment by alanclayton** [comment]
@alex-deaconu do you know what the issues were in the past? Do you recommend we do something different?

**Comment by alex-deaconu** [comment]
@alanclayton well for example recently I changed the Viewer's player registration help link. That was a static link as well. Nope, no recommendations, other than maybe not having a Start page at all for logged out users. Thanks.

**Comment by ByronDarlison** [comment]
@alex-deaconu I like that recommendation. Let's drop it. @alanclayton you concur?

**Comment by alanclayton** [comment]
@alex-deaconu @ByronDarlison Agreed. Drop it.

**Comment by alex-deaconu** [comment]
@ByronDarlison @alanclayton thanks!
