### ISSUE TITLE
Store does not load correctly on RVA in-app with html5mode enabled

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/rva#78]
@alanclayton @alex-deaconu and myself has discussed about an issue with RVA when using store with html5mode enabled. It is an easy fix and it will require a new RVA version to be deployed together with Store new version.

@robb-price found the issue when testing my changes this week https://github.com/Rise-Vision/store/issues/978.

Cheers

**Comment by alex-deaconu** [comment]
@alanclayton what is the priority for this compared to OAuth2 CH conversion? Thanks.

**Comment by alanclayton** [comment]
@rodrigopavezi I just talked to @robb-price and he is saying Rise-Vision/store#978 is no longer an issue. Can you confirm? @robb-price ??

@alex-deaconu just hang tight. I'll let you know once I hear back on the above.

**Comment by rodrigopavezi** [comment]
@alanclayton @robb-price it is an issue for the SEO changes on store. Card https://trello.com/c/dxiJVzM6/259-prerender-store-products-seo

We cannot have Metadata for each product without fixing this issue here.

cheers

**Comment by robb-price** [comment]
@alanclayton I tried this out again at http://rva-test.appspot.com, and all the issues listed in https://github.com/Rise-Vision/store/issues/978 are back. 

I asked @rodrigopavezi why this is and he informed me that he deployed the unfixed version back there for testing. So we don't need to reopen 978, we can just track it in here.

**Comment by alanclayton** [comment]
@robb-price to confirm, this is only occurring on rva-test. In-app Store on production is working as expected. Is that correct?

**Comment by robb-price** [comment]
@alanclayton That is correct. Everything is working as expected at http://rva.risevision.com and http://1-08-001.rvauser2.appspot.com/.

**Comment by alex-deaconu** [comment]
@alanclayton @robb-price @rodrigopavezi I should be able to fix this by the end of the day. Thanks.

**Comment by alanclayton** [comment]
@robb-price Thanks. @alex-deaconu do you want to take this after the oAuth2 issue?

**Comment by alanclayton** [comment]
@alex-deaconu Thanks

**Comment by alex-deaconu** [comment]
@robb-price @rodrigopavezi the necessary updates to the URL have been made at: 
http://1-07-029.rva-test.appspot.com/

Please verify. Thanks.

**Comment by robb-price** [comment]
@alex-deaconu @rodrigopavezi I can confirm that this is corrected at http://1-07-029.rva-test.appspot.com/

**Comment by ByronDarlison** [comment]
@alex-deaconu @robb-price what's left to close this issue? Thanks

**Comment by robb-price** [comment]
@ByronDarlison @alex-deaconu I'd prefer to close this once it is deployed and verified in production. That is all that remains.

**Comment by ByronDarlison** [comment]
@robb-price makes sense. Thanks

**Comment by alanclayton** [comment]
@robb-price I'm pretty sure this was deployed today w/ RVA version 1-08-003. @alex-deaconu Is that correct?

**Comment by alex-deaconu** [comment]
@alanclayton @robb-price that is correct. It was deployed yesterday. Thanks.

**Comment by robb-price** [comment]
@alanclayton @alex-deaconu Awesome, I am not seeing it at http://rva.risevision.com. Verified and Closed.
