### ISSUE TITLE
File selection modal in directory gadget appears behind placeholder

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rva#81]
Steps to reproduce:
1. In the directory gadget settings, click the "Google drive" link.

Result:
File selection modal appears behind placeholder (and settings modal)

How it should work:
File selection modal appears in front of other modals

Link to Presentation:
http://1-08-001.rvauser2.appspot.com/#/PRESENTATION_MANAGE/id=8932f449-9ddb-43aa-82a9-25612645ef46?cid=5a0bf731-b4d9-410a-9abe-5b3ab8277d44

OS:
Xubuntu 14.04

Chrome Ver:
Version 41.0.2272.101 (64-bit)

**Comment by alex-deaconu** [comment]
This is now fixed. Please verify. Thanks.

**Comment by btfrise** [comment]
Verified as fixed. Thanks @alex-deaconu. Closing.
