### ISSUE TITLE
Calendar does not appear when scheduling items.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#82]
Steps to reproduce:
1. Add an item to a placeholder
2. Under timeline for that item, click edit
3. Select start date or end date field.

Result:
No calendar is created.

How it should work:
A calendar should be created to allow users to select dates.

Notes:
This is an issue with all scheduling within RVA.

OS:
OS X

Chrome Ver:
41.0.2272.104

Screenshot:
http://www.screencast.com/t/aAFOylbf

**Comment by btfrise** [comment]
Verified as fixed. Thanks @alex-deaconu. Closing.

**Comment by alex-deaconu** [comment]
This is now fixed. Please verify. Thanks!
