### ISSUE TITLE
Errors loading RVA in default version and traffic split version

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rva#83]
Ran into several problems trying to load RVA last night and getting just a white screen.  Seems the problems are 404 errors and NPE errors in either version.

https://drive.google.com/folderview?id=0B_fkyfbDITdifkdaam9Cb2JHc1NwWDd5MEpyVm9LYVhoa2FORXVnd1lsVGFRU0phX0RzRFU&usp=sharing

Issue replicated this morning just by reloading rva.risevision.com repeatedly.  On the third reload it failed.

**Comment by ByronDarlison** [comment]
@alex-deaconu @tejohnso @alanclayton given traffic splitting is over can we close this defect? Thanks

**Comment by tejohnso** [comment]
Okay by me.

**Comment by alex-deaconu** [comment]
Yes, I believe this should be resolved. Thanks.

**Comment by ByronDarlison** [comment]
Thanks @tejohnso @alex-deaconu
