### ISSUE TITLE
Schedules: When editing timeline, changing weekly option affects all presentations in the schedule.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rva#89]
Steps to reproduce:
1. Create new blank schedule.
2. Add several (2+) presentations to this schedule.
3. Click a presentation, under timeline click edit.
4. Set timeline to weekly, 2 weeks.
5. Click another presentation, set to weekly, 7 weeks.

Result:
Every presentation that is set to weekly is now set to 7 weeks.

How it should work:
Each presentation should be able to be scheduled on it's own.

Link to sample schedule:
http://rva.risevision.com/#/SCHEDULE_MANAGE?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

Screen capture:
http://www.screencast.com/t/wB1JorZkf1KZ

OS:
OS X

Chrome Ver:
41.0.2272.104

**Comment by btfrise** [comment]
FYI @alanclayton

**Comment by alanclayton** [comment]
@alex-deaconu Can you take a look at this one tomorrow?

**Comment by alex-deaconu** [comment]
@alanclayton was off Friday. Will investigate today. Thanks.

**Comment by alex-deaconu** [comment]
@alanclayton @btfrise this is now fixed. Should this go out as a quick fix, or can it wait until the new RVA version w/ CH which is now in QA is deployed, or should I add this fix to that version? Thanks.

**Comment by alanclayton** [comment]
once @btfrise verifies the issue I'd say deploy. Thanks

**Comment by alex-deaconu** [comment]
@alanclayton okay. Will stage after RVA w/ CH version is deployed and he can verify. @btfrise will let you know when it's ready and the URL. Thanks.

**Comment by alex-deaconu** [comment]
@btfrise @alanclayton this issue has been fixed. Can be verified at http://1-08-005.rvauser2.appspot.com/. Thanks.
