### ISSUE TITLE
When you log in, the URL in the address bar contains the word "undefined".

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rva#90]
<b>How it works now:</b>
Log into rva.risevision.com. Notice that when it authenticates you, you see the word "undefined" in the URL. When you go to any page (Presentations, Displays, etc), undefined is replaced with the page name.

![2015-04-06_1500](https://cloud.githubusercontent.com/assets/6862256/7010248/b09445b8-dc6d-11e4-9fa4-c44803133f9a.png)

<b>How it should work:</b>
The text "undefined" should not show in the address bar URL.

**Comment by ByronDarlison** [comment]
Won't fix in RVA
