### ISSUE TITLE
When you try to delete a Presentation that is currently in a Schedule, you get an RPC failure instead of the message that it is currently in a schedule.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rva#92]
<b>How it works now:</b>
Try delete a Presentation that is currently being played in a Schedule. Notice that instead of the "This Presentation is currently in a Schedule" message that you normally get, you get an RPC Failure.

For further clarification: https://db.tt/gPjeH61W

Originally logged as https://github.com/Rise-Vision/core/issues/168.

**Comment by alex-deaconu** [comment]
@robb-price fixed at http://1-08-006.rvauser2.appspot.com/. Please verify. Thanks.

**Comment by robb-price** [comment]
@alex-deaconu Verified at http://1-08-006.rvauser2.appspot.com/. Will verify and close once deployed to production. Thanks!

**Comment by alex-deaconu** [comment]
@robb-price this fix is now deployed. Thanks.

**Comment by robb-price** [comment]
Verified and Closed.
