### ISSUE TITLE
Province list needs Nunavut changed from NV to NU

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rva#96]
Province List in the RVA settings needs to be updated so Nuavut returns NU instead of NV.

**Comment by ByronDarlison** [comment]
@robb-price is this issue open in the new apps or just RVA? And if just RVA please go ahead and close this...

**Comment by alex-deaconu** [comment]
@ByronDarlison @robb-price this was fixed. The correct province code `NU` is being used. Closing. Thanks.
