### ISSUE TITLE
Saving schedule timeline as "All Day" doesn't persist

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rva#99]
Steps to reproduce:
1.  Load  a schedule and save its timeline with a specific time of day range.
2.  Exit the schedules app
3.  Go back into the schedule and set the schedule's timeline to "All Day"
4.  Save and exit the schedule app
5.  Re-enter schedule app and notice that your changes weren't saved.

Video:
https://drive.google.com/file/d/0B_fkyfbDITdiUTRtMDFKLWpjMWM/view?usp=sharing

**Comment by ByronDarlison** [comment]
WOn't fix in RVA
